<a href="https://colab.research.google.com/github/davoodwadi/davoodwadi.github.io/blob/main/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
a = torch.tensor([[1,0,0],
                  [0,1,1],
                  [0,-1,1],
                  [0,1,1]],
                 ).float()
a

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0., -1.,  1.],
        [ 0.,  1.,  1.]])

In [3]:
k = 20
u = torch.randn(a.shape[0],k,
                 requires_grad=True)

e = torch.randn(k,k,
                 requires_grad=True)
v = torch.randn(k,a.shape[1],
                 requires_grad=True)
v

tensor([[ 0.3727,  0.4020, -0.5528],
        [-0.2050, -0.4838, -0.2506],
        [-1.5798, -0.2937,  1.2738],
        [ 1.0125,  0.5758,  0.0430],
        [ 0.1004,  0.9923,  0.5611],
        [-1.2531, -0.7247,  1.5790],
        [ 1.6918,  2.4901, -0.6655],
        [ 0.1845, -1.2979,  0.3447],
        [-0.8393,  0.1415,  1.4891],
        [-0.2766, -1.1580,  0.7771],
        [-0.4322,  0.8322,  0.2769],
        [-0.7442,  0.1456, -0.2111],
        [ 0.6675, -0.0240, -0.6332],
        [-2.3263, -0.6030,  0.5034],
        [ 0.5356, -0.0642, -0.4217],
        [-0.5647,  0.3019, -0.6941],
        [ 1.7027, -0.6539, -0.9952],
        [-0.0654,  0.4789, -0.3537],
        [-0.1381,  0.1470,  0.8018],
        [-2.5433,  0.3890,  0.0380]], requires_grad=True)

In [4]:
with torch.no_grad():
  print((u @ e) @ v)

tensor([[ 13.9237,  15.2582,  -9.2116],
        [  6.6544, -12.3802,  -4.2403],
        [-16.9099, -32.8751,  11.2544],
        [ 30.6219,  15.0554,  -2.8704]])


In [ ]:
a_hat = (u @ e) @ v
loss = loss_fn(a_hat[mask], a[mask])
loss.backward()

In [ ]:
u.grad

tensor([[-3.1585e+01, -2.1295e+00,  1.7229e+01, -2.9118e+01,  2.1858e+01,
         -1.0075e+01,  6.5761e+00,  1.2604e+01,  2.8173e+01, -7.5108e+00,
         -1.0504e+01,  6.2597e+00, -1.5025e+01, -2.1357e+01, -1.5101e+01,
          2.9773e+00,  5.2052e+00, -8.2106e+00,  3.6537e+00,  6.6837e+00],
        [-1.3986e+01,  2.6096e+00,  2.2352e+01,  2.4575e+01,  5.3397e+01,
         -2.3649e+01, -5.5750e+01,  2.2495e+01,  1.6939e+01, -3.0122e+01,
          2.9761e+01,  2.5503e+01,  2.6977e+01,  4.1092e+01,  3.7109e+00,
          1.0263e+01, -2.2510e+01,  2.8549e+01,  2.1062e+01,  2.0827e+01],
        [ 6.2770e+00,  1.3564e+01,  1.2677e+01,  3.1640e+01,  2.7399e+01,
         -1.6760e+01, -4.6806e+01,  5.5829e+00,  7.8993e-02, -2.5555e+01,
          2.7347e+01,  9.4444e+00,  1.7262e+01,  4.3731e+01,  1.8627e+01,
          2.1008e+01, -2.2945e+01,  1.8907e+01,  1.4966e+01,  6.5067e+00],
        [ 2.3790e+01,  4.6461e+00, -6.8382e+00,  3.5006e+01, -9.4395e-01,
         -3.7348e-02, -2.6268e+01, 

In [ ]:
u.shape

torch.Size([4, 20])

In [36]:
k = 20
u = torch.randn(a.shape[0],k,
                 requires_grad=True)

e = torch.randn(k,k,
                 requires_grad=True)
v = torch.randn(k,a.shape[1],
                 requires_grad=True)

In [37]:
optim = torch.optim.SGD([u, e, v], lr = 0.001, momentum=0)
loss_fn = torch.nn.MSELoss()
epoch = 20
mask = a >= 0
for ep in range(epoch):
  a_hat = (u @ e) @ v # added sigmoid to force (0, 1)
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%1==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')


epoch 0: loss 269.1609
epoch 1: loss 146.8698
epoch 2: loss 87.0954
epoch 3: loss 54.5714
epoch 4: loss 35.6558
epoch 5: loss 24.1037
epoch 6: loss 16.7645
epoch 7: loss 11.9434
epoch 8: loss 8.6836
epoch 9: loss 6.4236
epoch 10: loss 4.8222
epoch 11: loss 3.6658
epoch 12: loss 2.8168
epoch 13: loss 2.1845
epoch 14: loss 1.7076
epoch 15: loss 1.3441
epoch 16: loss 1.0642
epoch 17: loss 0.8469
epoch 18: loss 0.6770
epoch 19: loss 0.5433


In [ ]:
with torch.no_grad():
  print((u @ e) @ v)

tensor([[ 1.0000e+00, -7.4953e-06, -1.2398e-05],
        [-1.4305e-06,  1.0000e+00,  1.0000e+00],
        [-1.9073e-06,  3.4807e+00,  9.9999e-01],
        [ 5.7220e-06,  1.0000e+00,  9.9999e-01]])


In [ ]:
a

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0., -1.,  1.],
        [ 0.,  1.,  1.]])

# Get ActiveSGD algorithm
"Read The Signs" [paper](https://arxiv.org/abs/2301.10133)

PyTorch [optimizer](https://raw.githubusercontent.com/davoodwadi/active-lr/main/optimizers/ActiveSGD.py)

In [10]:
!wget https://raw.githubusercontent.com/davoodwadi/active-lr/main/optimizers/ActiveSGD.py

--2023-09-25 12:09:51--  https://raw.githubusercontent.com/davoodwadi/active-lr/main/optimizers/ActiveSGD.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4148 (4.1K) [text/plain]
Saving to: ‘ActiveSGD.py’

ActiveSGD.py        100%[===================>]   4.05K  --.-KB/s    in 0s      

2023-09-25 12:09:51 (68.1 MB/s) - ‘ActiveSGD.py’ saved [4148/4148]



In [11]:
from ActiveSGD import ActiveSGD

In [43]:
k = 20
u = torch.randn(a.shape[0],k,
                 requires_grad=True)

e = torch.randn(k,k,
                 requires_grad=True)
v = torch.randn(k,a.shape[1],
                 requires_grad=True)

In [44]:
stepSize = 1
optim = ActiveSGD([u, e, v], stepSize=1, lr = 0.001, momentum=0, lrLow=0.5, lrHigh=2.)
loss_fn = torch.nn.MSELoss()
epoch = 20
mask = a >= 0
for ep in range(epoch):
  a_hat = (u @ e) @ v # added sigmoid to force (0, 1)
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%1==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')

epoch 0: loss 401.8856
epoch 1: loss 204.4616
epoch 2: loss 121.5371
epoch 3: loss 74.8861
epoch 4: loss 46.9087
epoch 5: loss 29.4424
epoch 6: loss 18.3647
epoch 7: loss 11.3499
epoch 8: loss 6.9511
epoch 9: loss 4.2248
epoch 10: loss 2.5522
epoch 11: loss 1.5333
epoch 12: loss 0.9155
epoch 13: loss 0.5422
epoch 14: loss 0.3176
epoch 15: loss 0.1835
epoch 16: loss 0.1043
epoch 17: loss 0.0581
epoch 18: loss 0.0317
epoch 19: loss 0.0169


add a neural netwrok in the middle

In [45]:
class NN(torch.nn.Module):
  def __init__(self,a, hidden_size):
    super(NN, self).__init__()
    self.u = torch.nn.Linear(a.shape[0], hidden_size, bias=False)
    self.e1 = torch.nn.Linear(hidden_size, hidden_size)
    self.v = torch.nn.Linear(hidden_size, a.shape[1])
    self.relu = torch.nn.ReLU()
  def forward(self):
    x = self.e1(self.u.weight.T)
    x = self.relu(x)
    x = self.v(x)
    return x

In [47]:
hidden_size = 20
lr = 0.001
model = NN(a, hidden_size)
optim = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = torch.nn.MSELoss()

In [48]:
epoch = 100
mask = a >= 0
for ep in range(epoch):
  a_hat = model()
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%10==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')


epoch 0: loss 0.7275
epoch 10: loss 0.7156
epoch 20: loss 0.7040
epoch 30: loss 0.6926
epoch 40: loss 0.6815
epoch 50: loss 0.6707
epoch 60: loss 0.6601
epoch 70: loss 0.6498
epoch 80: loss 0.6397
epoch 90: loss 0.6298


ActiveSGD

In [55]:
hidden_size = 20
lr = 0.001
model = NN(a, hidden_size)
optim = ActiveSGD(model.parameters(), 1, lr=lr, lrHigh=2., lrLow=0.5)
loss_fn = torch.nn.MSELoss()

In [56]:
epoch = 100
mask = a >= 0
for ep in range(epoch):
  a_hat = model()
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%10==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')


epoch 0: loss 0.6306
epoch 10: loss 0.5806
epoch 20: loss 0.4504
epoch 30: loss 0.3030
epoch 40: loss 0.1950
epoch 50: loss 0.1383
epoch 60: loss 0.1081
epoch 70: loss 0.0785
epoch 80: loss 0.0492
epoch 90: loss 0.0243


In [57]:
with torch.no_grad():
  a_hat = model()

In [58]:
a_hat

tensor([[ 0.9203,  0.1739,  0.1112],
        [-0.0391,  0.8130,  0.9532],
        [ 0.0461,  0.4488,  0.9737],
        [ 0.0257,  1.0491,  0.9791]])

In [59]:
a

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0., -1.,  1.],
        [ 0.,  1.,  1.]])

Time series

In [60]:
a = torch.tensor([[1,-1],
                  [2,6],
                  [3,7],
                  [4,8]],
                 ).float()
a

tensor([[ 1., -1.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]])

In [61]:
hidden_size = 20
lr = 0.001
model = NN(a, hidden_size)
optim = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = torch.nn.MSELoss()

In [62]:
epoch = 100
mask = a >= 0
for ep in range(epoch):
  a_hat = model()
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%10==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')

epoch 0: loss 27.2724
epoch 10: loss 26.6480
epoch 20: loss 26.0484
epoch 30: loss 25.4727
epoch 40: loss 24.9193
epoch 50: loss 24.3772
epoch 60: loss 23.8444
epoch 70: loss 23.3177
epoch 80: loss 22.7949
epoch 90: loss 22.2743


ActiveSGD

In [63]:
hidden_size = 20
lr = 0.001
model = NN(a, hidden_size)
optim = ActiveSGD(model.parameters(), 1, lr=lr, lrHigh=2., lrLow=0.5)
loss_fn = torch.nn.MSELoss()

In [64]:
epoch = 100
mask = a >= 0
for ep in range(epoch):
  a_hat = model()
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%10==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')

epoch 0: loss 25.9642
epoch 10: loss 21.8671
epoch 20: loss 8.9271
epoch 30: loss 2.8119
epoch 40: loss 0.4167
epoch 50: loss 0.2853
epoch 60: loss 0.1742
epoch 70: loss 0.0756
epoch 80: loss 0.0228
epoch 90: loss 0.0072


In [65]:
with torch.no_grad():
  a_hat = model()
a_hat

tensor([[0.9897, 3.7320],
        [2.0361, 6.0216],
        [3.0824, 6.9881],
        [3.9730, 8.0825]])

In [66]:
a

tensor([[ 1., -1.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]])