<a href="https://colab.research.google.com/github/davoodwadi/davoodwadi.github.io/blob/main/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [209]:
a = torch.tensor([[1,0,0],
                  [0,1,1],
                  [0,-1,1],
                  [0,1,1]],
                 ).float()
a

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0., -1.,  1.],
        [ 0.,  1.,  1.]])

In [210]:
k = 20
u = torch.randn(a.shape[0],k,
                 requires_grad=True)

e = torch.randn(k,k,
                 requires_grad=True)
v = torch.randn(k,a.shape[1],
                 requires_grad=True)
v

tensor([[ 0.9015,  1.0255,  0.2431],
        [-1.2664, -0.6683,  0.5521],
        [ 0.4850,  0.2404,  0.5693],
        [-1.1650,  0.4653,  0.5886],
        [ 0.7403,  0.4950,  0.9561],
        [ 0.9427,  0.0692, -0.7072],
        [-0.7861,  1.5624, -0.1903],
        [ 0.6444,  1.6078, -1.1009],
        [-0.8088,  1.7394,  0.7134],
        [-1.0839, -1.8242,  0.6143],
        [-0.8885,  0.5079,  0.9730],
        [-0.3428,  0.5006,  1.0436],
        [-1.1146, -0.7251, -0.0483],
        [-0.7944, -0.5456,  0.5030],
        [ 0.2012, -0.5444, -0.7391],
        [ 0.5292,  0.3408, -1.0711],
        [-1.6246,  1.8258, -0.8090],
        [-0.9683, -0.0782, -2.0903],
        [-0.5788, -1.1266, -1.1112],
        [ 0.3413,  0.5070, -0.4971]], requires_grad=True)

In [211]:
with torch.no_grad():
  print((u @ e) @ v)

tensor([[ -6.4249,  20.2877,   3.4491],
        [ 27.2574,  12.4964,   4.0062],
        [ 22.9396,  19.2870, -10.5043],
        [ 16.3157, -13.0167,  -3.0784]])


In [212]:
a_hat = (u @ e) @ v
loss = loss_fn(a_hat[mask], a[mask])
loss.backward()

In [213]:
u.grad

tensor([[-3.1585e+01, -2.1295e+00,  1.7229e+01, -2.9118e+01,  2.1858e+01,
         -1.0075e+01,  6.5761e+00,  1.2604e+01,  2.8173e+01, -7.5108e+00,
         -1.0504e+01,  6.2597e+00, -1.5025e+01, -2.1357e+01, -1.5101e+01,
          2.9773e+00,  5.2052e+00, -8.2106e+00,  3.6537e+00,  6.6837e+00],
        [-1.3986e+01,  2.6096e+00,  2.2352e+01,  2.4575e+01,  5.3397e+01,
         -2.3649e+01, -5.5750e+01,  2.2495e+01,  1.6939e+01, -3.0122e+01,
          2.9761e+01,  2.5503e+01,  2.6977e+01,  4.1092e+01,  3.7109e+00,
          1.0263e+01, -2.2510e+01,  2.8549e+01,  2.1062e+01,  2.0827e+01],
        [ 6.2770e+00,  1.3564e+01,  1.2677e+01,  3.1640e+01,  2.7399e+01,
         -1.6760e+01, -4.6806e+01,  5.5829e+00,  7.8993e-02, -2.5555e+01,
          2.7347e+01,  9.4444e+00,  1.7262e+01,  4.3731e+01,  1.8627e+01,
          2.1008e+01, -2.2945e+01,  1.8907e+01,  1.4966e+01,  6.5067e+00],
        [ 2.3790e+01,  4.6461e+00, -6.8382e+00,  3.5006e+01, -9.4395e-01,
         -3.7348e-02, -2.6268e+01, 

In [214]:
u.shape

torch.Size([4, 20])

In [190]:
optim = torch.optim.SGD([u, e, v], lr = 0.001)
loss_fn = torch.nn.MSELoss()
epoch = 1000
mask = a >= 0
for ep in range(epoch):
  a_hat = (u @ e) @ v # added sigmoid to force (0, 1)
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%100==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')


epoch 0: loss 139.4312
epoch 100: loss 0.0049
epoch 200: loss 0.0000
epoch 300: loss 0.0000
epoch 400: loss 0.0000
epoch 500: loss 0.0000
epoch 600: loss 0.0000
epoch 700: loss 0.0000
epoch 800: loss 0.0000
epoch 900: loss 0.0000


In [191]:
with torch.no_grad():
  print((u @ e) @ v)

tensor([[ 1.0000e+00, -7.4953e-06, -1.2398e-05],
        [-1.4305e-06,  1.0000e+00,  1.0000e+00],
        [-1.9073e-06,  3.4807e+00,  9.9999e-01],
        [ 5.7220e-06,  1.0000e+00,  9.9999e-01]])


In [192]:
a

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0., -1.,  1.],
        [ 0.,  1.,  1.]])

In [180]:
a_hat[mask], a[mask]

(tensor([ 1.0000e+00,  0.0000e+00, -2.3842e-07,  1.0000e+00,  0.0000e+00],
        grad_fn=<IndexBackward0>),
 tensor([1., 0., 0., 1., 0.]))

add a neural netwrok in the middle

In [200]:
class NN(torch.nn.Module):
  def __init__(self,a, hidden_size):
    super(NN, self).__init__()
    self.u = torch.nn.Linear(a.shape[0], hidden_size, bias=False)
    self.e1 = torch.nn.Linear(hidden_size, hidden_size)
    self.v = torch.nn.Linear(hidden_size, a.shape[1])
    self.relu = torch.nn.ReLU()
  def forward(self):
    x = self.e1(self.u.weight.T)
    x = self.relu(x)
    x = self.v(x)
    return x

In [215]:
hidden_size = 20
lr = 0.001
model = NN(a, hidden_size)
optim = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = torch.nn.MSELoss()

In [217]:
epoch = 10000
mask = a >= 0
for ep in range(epoch):
  a_hat = model()
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%1000==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')


epoch 0: loss 0.2243
epoch 100: loss 0.2116
epoch 200: loss 0.2001
epoch 300: loss 0.1898
epoch 400: loss 0.1804
epoch 500: loss 0.1718
epoch 600: loss 0.1637
epoch 700: loss 0.1563
epoch 800: loss 0.1492
epoch 900: loss 0.1426
epoch 1000: loss 0.1362
epoch 1100: loss 0.1301
epoch 1200: loss 0.1242
epoch 1300: loss 0.1185
epoch 1400: loss 0.1129
epoch 1500: loss 0.1075
epoch 1600: loss 0.1023
epoch 1700: loss 0.0971
epoch 1800: loss 0.0921
epoch 1900: loss 0.0872
epoch 2000: loss 0.0825
epoch 2100: loss 0.0780
epoch 2200: loss 0.0737
epoch 2300: loss 0.0694
epoch 2400: loss 0.0652
epoch 2500: loss 0.0612
epoch 2600: loss 0.0573
epoch 2700: loss 0.0535
epoch 2800: loss 0.0499
epoch 2900: loss 0.0465
epoch 3000: loss 0.0431
epoch 3100: loss 0.0400
epoch 3200: loss 0.0370
epoch 3300: loss 0.0342
epoch 3400: loss 0.0316
epoch 3500: loss 0.0291
epoch 3600: loss 0.0268
epoch 3700: loss 0.0247
epoch 3800: loss 0.0227
epoch 3900: loss 0.0208
epoch 4000: loss 0.0191
epoch 4100: loss 0.0175
epoc

In [218]:
with torch.no_grad():
  a_hat = model()

In [219]:
a_hat

tensor([[ 1.0052,  0.0095,  0.0043],
        [-0.0270,  0.9689,  0.9363],
        [ 0.0084,  0.9217,  1.0360],
        [ 0.0139,  1.0079,  1.0017]])

In [220]:
a

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0., -1.,  1.],
        [ 0.,  1.,  1.]])

Time series

In [221]:
a = torch.tensor([[1,-1],
                  [2,6],
                  [3,7],
                  [4,8]],
                 ).float()
a

tensor([[ 1., -1.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]])

In [222]:
hidden_size = 20
lr = 0.001
model = NN(a, hidden_size)
optim = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = torch.nn.MSELoss()

In [223]:
epoch = 10000
mask = a >= 0
for ep in range(epoch):
  a_hat = model()
  loss = loss_fn(a_hat[mask], a[mask])
  loss.backward()
  optim.step()
  optim.zero_grad()
  if ep%1000==0:
    print(f'epoch {ep}: loss {loss.detach().item():0.4f}')

epoch 0: loss 25.8822
epoch 1000: loss 0.0961
epoch 2000: loss 0.0413
epoch 3000: loss 0.0239
epoch 4000: loss 0.0134
epoch 5000: loss 0.0071
epoch 6000: loss 0.0036
epoch 7000: loss 0.0019
epoch 8000: loss 0.0010
epoch 9000: loss 0.0005


In [225]:
with torch.no_grad():
  a_hat = model()
a_hat

tensor([[1.0000, 2.8161],
        [2.0031, 5.9983],
        [3.0273, 6.9852],
        [3.9747, 8.0136]])

In [226]:
a

tensor([[ 1., -1.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]])